export const projects = [
	{
		title: 'Loopy Lotto',
		titleCode: '<p>hel<span>l</span>o</p>',
		subtitle: 'A lottery game with a twist!',
		description:
			'A pay-to-play app in which my family members all participate and can check game progress based on the real life lottery draws. I designed this from scratch and is developed using vanilla javascript. ',
		image: '/images/ll.png',
		bgimage: '/images/bg_balls.png',
		bgid: 'card-temp',
		cardclass: 'left',
		tags: ['Vanilla JS', 'SCSS', 'ES6 Syntax'],
		icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
		source: 'https://relaxed-dijkstra-f29d44.netlify.app/',
		visit: 'https://github.com/DaveDevPerry/LoopyLottoMVP',
		font: 'font-loopy-lotto',
		id: 0,
	},
	{
		title: 'guitARCHIVE',
		titleCode: '<h3>guit<span>ARCHIVE</span></h3>',
		subtitle: 'An easy to access storage solution for my sheet music',
		description:
			'An app for me to keep all my sheet music in one place that I can access from any device when needed. It also keeps track of my progress and songs to prioritize practicing to upload to my YouTube channel.  ',
		image: '/images/ga.png',
		bgimage: '/images/bg_guitar1.png',
		bgid: 'card-temp',
		cardclass: 'right',
		tags: ['3rd Party API', 'React', 'Node'],
		icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
		source: 'https://heuristic-newton-ad6a42.netlify.app/',
		visit: 'https://github.com/DaveDevPerry/guitARCHIVE',
		font: 'font-guitar-archive',
		id: 1,
	},
	{
		title: 'TERROR-Fi',
		titleCode: `<p>TEST</p>`,
		subtitle: 'Streaming un-released Terrorvision demo tracks',
		description:
			'A single page app built for Terrorvision fans to easily stream rare demo songs from the bands early days.  Containing custom animations and an audio visualizer to provide a great user experience',
		image: '/images/tf.png',
		bgimage: '/images/bg_cans.png',
		bgid: 'card-temp',
		cardclass: 'left',
		tags: ['Vanilla JS', 'ES6 Syntax', 'Animations'],
		icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
		source: 'https://terror-fi.netlify.app/',
		visit: 'https://github.com/DaveDevPerry/Terror-Fi_v1',
		font: 'font-terror-fi',
		id: 2,
	},
	{
		title: "Pinks N' Purples",
		titleCode: `<p>TEST</p>`,
		subtitle: 'A custom two-player game of naughts & crosses',
		description:
			'A game specifically built for my four and six year old nieces to play on their tablet together. It is a re-imagining of Tic-Tac-Toe',
		image: '/images/pp.png',
		bgimage: '/images/bg_game.png',
		bgid: 'card-temp',
		cardclass: 'left',
		tags: ['Vanilla JS', 'LocalStorage', 'Firebase'],
		icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
		source: 'https://goofy-swartz-1ec98c.netlify.app/',
		visit: 'https://github.com/DaveDevPerry/tic-tac-toe',
		font: 'font-pinks-n-purples',
		id: 3,
	},

	{
		title: 'Made 2 Measure',
		titleCode: `<p>TEST</p>`,
		subtitle: "An app to log your child's height as they grow",
		description:
			'A CRUD based, user authenticated, fully responsive application to record your kids height as they grow.',
		image: '/images/m2m.png',
		bgimage: '/images/bg_m2m.png',
		bgid: 'card-temp',
		cardclass: 'right',
		tags: ['Express.js', 'Node.js', 'MongoDb'],
		icons: ['FaNodeJs', 'FaExpress', 'SiMongodb'],
		source: 'https://made-to-measure.herokuapp.com/',
		visit: 'https://github.com/DaveDevPerry/made-to-measure',
		font: 'font-m2m',
		id: 4,
	},
	{
		title: 'Some People Say',
		titleCode: `<p>TEST</p>`,
		subtitle: 'Fan based lyric collaboration',
		description:
			'An app built solely for fans to collaborate missing lyrics to songs.  Based on a voting system to produce the lyrics that are most likely to be correct.',
		image: '/images/sps.png',
		bgimage: '/images/bg_mic.png',
		bgid: 'card-temp',
		cardclass: 'right',
		tags: ['SPA', 'MERN Stack', 'User Auth'],
		icons: ['SiNodedotjs', 'SiExpress', 'SiMongodb'],
		source: 'https://tv-lyrics-test-v2.herokuapp.com/',
		visit: 'https://github.com/DaveDevPerry/tv-lyric-library-v2',
		font: 'font-some-people-say',

		id: 5,
	},
	// {
	// 	title: 'TV Times',
	// 	titleCode: `<p>TEST</p>`,
	// 	subtitle: 'Terrorvision tour and gig listings site',
	// 	description:
	// 		'A CRUD based, fully responsive band gig history site enabling the users to add dates and set lists for missing gigs.',
	// 	image: '/images/tvtimes.png',
	// 	bgimage: '/images/bg_band.png',
	// 	bgid: 'card-temp',
	// 	cardclass: 'right',
	// 	tags: ['GraphCMS', 'Next.js', 'Firebase'],
	// 	source: 'https://goofy-swartz-1ec98c.netlify.app/',
	// 	visit: 'https://github.com/DaveDevPerry/tic-tac-toe',
	// 	font: 'font-tv-times',
	// 	id: 6,
	// },
];

// export const loaders = [
// 	{
// 		title: 'Keyframes',
// 		image: '/images/loader_tf.png',
// 		id: 0,
// 	},
// 	{
// 		title: 'GSAP',
// 		image: '/images/loader_ga.png',
// 		id: 1,
// 	},
// 	{
// 		title: 'Javascript',
// 		image: '/images/loader_lp.png',
// 		id: 2,
// 	},
// ];

export const TimeLineData = [
	{ year: 2020, text: 'Coded my first app' },
	{ year: 2021, text: 'Building Portfolio Projects' },
	{ year: 2022, text: 'Looking for employment' },
];
