export const projects = [
	{
		title: 'guitARCHIVE',
		titleCode: '<h3>guit<span>ARCHIVE</span></h3>',
		subtitle: 'An easy to access storage solution for sheet music',
		description:
			'A storage solution for all my sheet music that I can access from any device.  Allowing me to track my progress and songs to prioritize practicing to upload to my YouTube channel.',
		image: '/images/screen_guitarchive.webp',
		// image: '/images/ga.webp',
		bgimage: '/images/bg_gtr_off.png',
		// bgimage: '/images/bg_guitar1.webp',
		bgimageOn: '/images/bg_gtr_on.png',
		// bgimageOn: '/images/bg_guitar_red.webp',
		bgid: 'card-temp',
		bgidOn: 'card-temp-on',
		cardclass: 'left',
		tags: ['3rd Party API', 'React', 'Node'],
		icons: [
			{ name: 'SiMongodb', color: '#459546' },
			{ name: 'Express', color: '#234565' },
			{ name: 'SiReact', color: '#00CDF2' },
			{ name: 'FaNodeJs', color: '#6cc24a' },
		],
		qrSite: '/images/qr-ga.png',
		source: 'https://guitarchive-client.vercel.app',
		visit: 'https://github.com/DaveDevPerry/guitARCHIVE',
		login: ['email: demo@dpga.com', 'password: S4v4nn4h123!'],
		siteLogin: ['email', 'demo@dpga.com'],
		sitePassword: ['password', 'S4v4nn4h123!'],
		hostIcon: { name: 'IoLogoVercel', color: '#000000' },
		// hostIcon: { name: 'SiNetlify', color: '#000000' },
		// hostIcon: { name: 'SiVercel', color: '#000000' },
		codeFront: 'https://github.com/DaveDevPerry/guitarchive_client',
		codeBack: 'https://github.com/DaveDevPerry/guitarchive_server',
		font: 'font-guitar-archive',

		id: 0,
	},
	{
		title: 'Gig List',
		titleCode: '<p>hel<span>l</span>o</p>',
		subtitle: 'Track and store user specific gig list!',
		description:
			'An app to keep track of gigs you have seen and any that are coming up. I designed this for mobile and it is developed using the MERN stack.',
		image: '/images/screen_gigs.webp',
		bgimage: '/images/bg_band.webp',
		bgimageOn: '/images/bg_band_on.webp',
		bgid: 'card-temp',
		bgidOn: 'card-temp-on',
		cardclass: 'right',
		tags: ['user accounts', 'jwt', 'chart-js'],
		// icons: ['SiReact', 'SiPwa', 'SiCss3'],
		// colors: ['#000000', '#fff444', '#dd66uu'],
		icons: [
			{ name: 'SiMongodb', color: '#459546' },
			{ name: 'Express', color: '#234565' },
			{ name: 'SiReact', color: '#00CDF2' },
			{ name: 'FaNodeJs', color: '#6cc24a' },
		],
		// colors: ['#000000', '#fff444', '#dd66uu'],
		qrSite: '/images/qr-ga.png',
		source: 'https://noms-gig-list.vercel.app/',
		visit: 'https://github.com/DaveDevPerry/noms-gig-list',
		login: ['email: demo@dpgl.com', 'password: S4v4nn4h123!'],
		siteLogin: ['email', 'demo@dpgl.com'],
		sitePassword: ['password', 'S4v4nn4h123!'],
		hostIcon: { name: 'IoLogoVercel', color: '#000000' },
		codeFront: 'https://github.com/DaveDevPerry/noms-gig-list',
		codeBack: 'https://github.com/DaveDevPerry/gig-list_server',
		font: 'font-gig-list',
		id: 1,
	},
	{
		title: 'TERROR-Fi',
		titleCode: `<p>TEST</p>`,
		subtitle: 'Streaming un-released Terrorvision demo tracks',
		description:
			'A single page app built for Terrorvision fans to easily stream rare demo songs from the bands early days.  Containing custom animations and an audio visualizer to provide a great user experience.',
		image: '/images/screen_terrorfi.webp',
		bgimage: '/images/bg_cans.webp',
		bgimageOn: '/images/bg_cans_red.webp',
		bgid: 'card-temp',
		bgidOn: 'card-temp-on',
		cardclass: 'left',
		tags: ['HTML Canvas API', 'Custom Animations', 'Mobile Responsive'],
		// icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
		icons: [
			{ name: 'SiMongodb', color: '#459546' },
			{ name: 'Express', color: '#234565' },
			{ name: 'SiReact', color: '#00CDF2' },
			{ name: 'FaNodeJs', color: '#6cc24a' },
		],
		// colors: ['#000000', '#fff444', '#dd66uu'],
		qrSite: '/images/qr-ga.png',
		source: 'https://terror-fi-mern.vercel.app',
		visit: 'https://github.com/DaveDevPerry/terror-fi_mern',
		login: ['email: demo@dptf.com', 'password: S4v4nn4h123!'],
		siteLogin: ['email', 'demo@dptf.com'],
		sitePassword: ['password', 'S4v4nn4h123!'],
		hostIcon: { name: 'SiMongodb', color: '#459546' },
		codeFront: 'https://github.com/DaveDevPerry/terror-fi_mern',
		codeBack: 'https://github.com/DaveDevPerry/why-weight_server',
		font: 'font-terror-fi',
		id: 2,
	},
	{
		title: 'Why Weight?',
		titleCode: '<p>hel<span>l</span>o</p>',
		subtitle: 'Weight tracking app!',
		description:
			'An app to keep track of all your weight. Not only that, but you can create a group and invite friends to join and this displays progress in the form of a league.',
		image: '/images/screen_whyweight.webp',
		bgimage: '/images/bg_scales.webp',
		bgimageOn: '/images/bg_scales_on.webp',
		bgid: 'card-temp',
		bgidOn: 'card-temp-on',
		cardclass: 'right',
		tags: ['user accounts', 'bcrypt', 'chart-js'],
		// icons: ['SiReact', 'SiPwa', 'SiCss3'],
		// colors: ['#000000', '#fff444', '#dd66uu'],
		icons: [
			{ name: 'SiMongodb', color: '#459546' },
			{ name: 'Express', color: '#234565' },
			{ name: 'SiReact', color: '#00CDF2' },
			{ name: 'FaNodeJs', color: '#6cc24a' },
		],
		// colors: ['#000000', '#fff444', '#dd66uu'],
		qrSite: '/images/qr-ga.png',
		source: 'https://why-weight.vercel.app',
		visit: 'https://github.com/DaveDevPerry/why-weight',
		login: ['email: demo@dpww.com', 'password: S4v4nn4h123!'],
		siteLogin: ['email', 'demo@dpww.com'],
		sitePassword: ['password', 'S4v4nn4h123!'],
		hostIcon: { name: 'IoLogoVercel', color: '#000000' },
		// hostIcon: { name: 'SiNetlify', color: '#000000' },
		// hostIcon: { name: 'SiVercel', color: '#000000' },
		codeFront: 'https://github.com/DaveDevPerry/why-weight',
		codeBack: 'https://github.com/DaveDevPerry/why-weight_server',
		font: 'font-why-weight',
		id: 3,
	},
	// {
	// 	title: 'Gig List',
	// 	titleCode: '<p>hel<span>l</span>o</p>',
	// 	subtitle: 'Track and store user specific gig list!',
	// 	description:
	// 		'An app to keep track of gigs you have seen and any that are coming up. I designed this for mobile and it is developed using the MERN stack.',
	// 	image: '/images/screen_gigs.webp',
	// 	bgimage: '/images/bg_band.webp',
	// 	bgimageOn: '/images/bg_band_on.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'left',
	// 	tags: ['user accounts', 'jwt', 'chart-js'],
	// 	// icons: ['SiReact', 'SiPwa', 'SiCss3'],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	icons: [
	// 		{ name: 'SiMongodb', color: '#459546' },
	// 		{ name: 'Express', color: '#234565' },
	// 		{ name: 'SiReact', color: '#00CDF2' },
	// 		{ name: 'FaNodeJs', color: '#6cc24a' },
	// 	],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	source: 'https://noms-gig-list.vercel.app/',
	// 	visit: 'https://github.com/DaveDevPerry/noms-gig-list',
	// 	login: ['email: demo@dpgl.com', 'password: S4v4nn4h123!'],
	// 	siteLogin: ['email', 'demo@dpgl.com'],
	// 	sitePassword: ['password', 'S4v4nn4h123!'],
	// 	hostIcon: { name: 'IoLogoVercel', color: '#000000' },
	// 	codeFront: 'https://github.com/DaveDevPerry/noms-gig-list',
	// 	codeBack: 'https://github.com/DaveDevPerry/gig-list_server',
	// 	font: 'font-gig-list',
	// 	id: 6,
	// },
	// {
	// 	title: 'TERROR-Fi',
	// 	titleCode: `<p>TEST</p>`,
	// 	subtitle: 'Streaming un-released Terrorvision demo tracks',
	// 	description:
	// 		'A single page app built for Terrorvision fans to easily stream rare demo songs from the bands early days.  Containing custom animations and an audio visualizer to provide a great user experience.',
	// 	image: '/images/screen_terrorfi.webp',
	// 	bgimage: '/images/bg_cans.webp',
	// 	bgimageOn: '/images/bg_cans_red.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'left',
	// 	tags: ['HTML Canvas API', 'Custom Animations', 'Mobile Responsive'],
	// 	// icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
	// 	icons: [
	// 		{ name: 'SiMongodb', color: '#459546' },
	// 		{ name: 'Express', color: '#234565' },
	// 		{ name: 'SiReact', color: '#00CDF2' },
	// 		{ name: 'FaNodeJs', color: '#6cc24a' },
	// 	],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	source: 'https://terror-fi-mern.vercel.app',
	// 	visit: 'https://github.com/DaveDevPerry/terror-fi_mern',
	// 	login: ['email: demo@dptf.com', 'password: S4v4nn4h123!'],
	// 	siteLogin: ['email', 'demo@dptf.com'],
	// 	sitePassword: ['password', 'S4v4nn4h123!'],
	// 	hostIcon: { name: 'SiMongodb', color: '#459546' },
	// 	codeFront: 'https://github.com/DaveDevPerry/terror-fi_mern',
	// 	codeBack: 'https://github.com/DaveDevPerry/why-weight_server',
	// 	font: 'font-terror-fi',
	// 	id: 4,
	// },
	// {
	// 	title: 'terrorQUIZion',
	// 	titleCode: '<p>hel<span>l</span>o</p>',
	// 	subtitle: 'Name the song quiz app',
	// 	description:
	// 		'An app in which fans of the band Terrorvision can test their knowledge of Terrorvision songs based on short audio samples.',
	// 	image: '/images/screen_terrorquizion.webp',
	// 	bgimage: '/images/bg_quiz.webp',
	// 	bgimageOn: '/images/bg_quiz_on.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'left',
	// 	tags: ['user accounts', 'bcrypt', 'framer-motion'],
	// 	// icons: ['SiReact', 'SiPwa', 'SiCss3'],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	icons: [
	// 		{ name: 'SiMongodb', color: '#459546' },
	// 		{ name: 'Express', color: '#234565' },
	// 		{ name: 'SiReact', color: '#00CDF2' },
	// 		{ name: 'FaNodeJs', color: '#6cc24a' },
	// 	],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	source: 'https://terrorvision-quiz.vercel.app',
	// 	visit: 'https://github.com/DaveDevPerry/tv-quiz',
	// 	login: ['email: demo@dptq.com', 'password: S4v4nn4h123!'],
	// 	siteLogin: ['email', 'demo@dptq.com'],
	// 	sitePassword: ['password', 'S4v4nn4h123!'],
	// 	hostIcon: { name: 'IoLogoVercel', color: '#000000' },
	// 	codeFront: 'https://github.com/DaveDevPerry/tv-quiz',
	// 	codeBack: 'https://github.com/DaveDevPerry/tv-quiz_server',
	// 	font: 'font-terrorquizion',
	// 	id: 8,
	// },
	// {
	// 	title: 'TV Fan Poll',
	// 	titleCode: '<h3>FUN<span>jumble</span></h3>',
	// 	subtitle: 'Create a poll and place your votes',
	// 	description:
	// 		'A fully responsive MERN Stack App I built for fan to fan interaction by creating polls and placing votes on everything Terrorvision related.  ',
	// 	image: '/images/tvp-screens.webp',
	// 	bgimage: '/images/bg_vote.webp',
	// 	bgimageOn: '/images/bg_vote.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'right',
	// 	tags: ['JSON WebToken', 'Password Hashing', 'axios', 'Theme Toggle'],
	// 	// icons: ['SiReact', 'SiPwa', 'SiCss3'],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	icons: [
	// 		{ name: 'SiMongodb', color: '#459546' },
	// 		{ name: 'Express', color: '#234565' },
	// 		{ name: 'SiReact', color: '#00CDF2' },
	// 		{ name: 'FaNodeJs', color: '#6cc24a' },
	// 	],
	// 	source: 'https://illustrious-travesseiro-d45285.netlify.app/',
	// 	visit: 'https://github.com/DaveDevPerry/tv-voting-app',
	// 	login: ['username: demo', 'password: demo123'],
	// 	siteLogin: ['username', 'demo'],
	// 	sitePassword: ['password', 'demo123'],
	// 	hostIcon: { name: 'SiNetlify', color: '#1186b4' },
	// 	codeFront: 'https://github.com/DaveDevPerry/tv-voting-app',
	// 	codeBack: 'https://github.com/DaveDevPerry/tv-voting-app',
	// 	font: 'font-tv-fan-poll',
	// 	id: 0,
	// },
	// {
	// 	title: 'FUNjumble',
	// 	titleCode: '<h3>FUN<span>jumble</span></h3>',
	// 	subtitle: 'A fun word game with several play modes',
	// 	description:
	// 		'A Progressive Web App of a selection of word games, updated daily, for the user to enjoy, share and track progress.  I designed this from scratch after the success of Wordle.',
	// 	image: '/images/funjumble.webp',
	// 	bgimage: '/images/bg_tiles.webp',
	// 	bgimageOn: '/images/bg_tiles.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'right',
	// 	tags: ['Progressive Web App', 'Chart.js', '3rd Party API', 'local storage'],
	// 	// icons: ['SiReact', 'SiPwa', 'SiCss3'],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	icons: [
	// 		{ name: 'SiReact', color: '#00CDF2' },
	// 		{ name: 'Chart', color: '#234565' },
	// 		{ name: 'SiCss3', color: '#1D6CAD' },
	// 	],
	// 	source: 'https://amazing-crepe-368e6b.netlify.app/',
	// 	// source: 'https://bit.ly/FUNjumble',
	// 	visit: 'https://github.com/DaveDevPerry/un-jumble-pwa',
	// 	login: [],
	// 	siteLogin: null,
	// 	sitePassword: null,
	// 	hostIcon: { name: 'SiNetlify', color: '#1186b4' },
	// 	codeFront: 'https://github.com/DaveDevPerry/un-jumble-pwa',
	// 	codeBack: null,
	// 	font: 'font-funjumble',
	// 	id: 1,
	// },
	// {
	// 	title: 'Some People Say',
	// 	titleCode: `<p>TEST</p>`,
	// 	subtitle: 'Fan based lyric collaboration',
	// 	description:
	// 		'An app built solely for fans to collaborate missing lyrics to songs.  Based on a voting system to produce the lyrics that are most likely to be correct.',
	// 	image: '/images/sps.webp',
	// 	bgimage: '/images/bg_mic.webp',
	// 	bgimageOn: '/images/bg_mic.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'right',
	// 	tags: ['SPA', 'MERN Stack', 'User Auth'],
	// 	// icons: ['SiNodedotjs', 'SiExpress', 'SiMongodb'],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	icons: [
	// 		{ name: 'SiMongodb', color: '#459546' },
	// 		{ name: 'Express', color: '#234565' },
	// 		{ name: 'FaNodeJs', color: '#6cc24a' },
	// 		{ name: 'SiSass', color: '#CD6799' },
	// 	],
	// 	source: 'https://some-people-say-server.onrender.com/',
	// 	visit: 'https://github.com/DaveDevPerry/tv-lyric-library-v2',
	// 	login: ['email: demo@demo.com', 'password: demo123'],
	// 	siteLogin: ['email', 'demo@demo.com'],
	// 	sitePassword: ['password', 'demo123'],
	// 	hostIcon: { name: 'IoLogoVercel', color: '#000000' },
	// 	codeFront: null,
	// 	codeBack: 'https://github.com/DaveDevPerry/tv-lyric-library-v2',
	// 	font: 'font-some-people-say',

	// 	id: 2,
	// },

	// {
	// 	title: 'Made 2 Measure',
	// 	titleCode: `<p>TEST</p>`,
	// 	subtitle: "An app to log your child's height as they grow",
	// 	description:
	// 		'A CRUD based, user authenticated, fully responsive application to record your kids height as they grow.',
	// 	image: '/images/m2m.webp',
	// 	bgimage: '/images/bg_m2m.webp',
	// 	bgid: 'card-temp',
	// 	cardclass: 'right',
	// 	tags: ['JSON WebToken', 'Password Hashing', 'FilePond'],
	// 	// icons: ['SiNodedotjs', 'SiSass', 'SiMongodb'],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	icons: [
	// 		{ name: 'SiMongodb', color: '#459546' },
	// 		{ name: 'Express', color: '#234565' },
	// 		{ name: 'FaNodeJs', color: '#6cc24a' },
	// 		{ name: 'SiCss3', color: '#1D6CAD' },
	// 	],
	// 	source: 'https://made-to-measure.herokuapp.com/',
	// 	visit: 'https://github.com/DaveDevPerry/made-to-measure',
	// 	login: ['email: test@email.com', 'password: 123456'],

	// 	font: 'font-m2m',
	// 	id: 3,
	// },

	// {
	// 	title: 'TERROR-Fi',
	// 	titleCode: `<p>TEST</p>`,
	// 	subtitle: 'Streaming un-released Terrorvision demo tracks',
	// 	description:
	// 		'A single page app built for Terrorvision fans to easily stream rare demo songs from the bands early days.  Containing custom animations and an audio visualizer to provide a great user experience.',
	// 	image: '/images/screen_terrorfi.webp',
	// 	bgimage: '/images/bg_cans.webp',
	// 	bgimageOn: '/images/bg_cans_red.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'left',
	// 	tags: ['HTML Canvas API', 'Custom Animations', 'Mobile Responsive'],
	// 	// icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
	// 	icons: [
	// 		{ name: 'SiMongodb', color: '#459546' },
	// 		{ name: 'Express', color: '#234565' },
	// 		{ name: 'SiReact', color: '#00CDF2' },
	// 		{ name: 'FaNodeJs', color: '#6cc24a' },
	// 	],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	source: 'https://terror-fi-mern.vercel.app',
	// 	visit: 'https://github.com/DaveDevPerry/terror-fi_mern',
	// 	login: ['email: demo@dptf.com', 'password: S4v4nn4h123!'],

	// 	font: 'font-terror-fi',
	// 	id: 4,
	// },
	// {
	// 	title: 'TERROR-Fi',
	// 	titleCode: `<p>TEST</p>`,
	// 	subtitle: 'Streaming un-released Terrorvision demo tracks',
	// 	description:
	// 		'A single page app built for Terrorvision fans to easily stream rare demo songs from the bands early days.  Containing custom animations and an audio visualizer to provide a great user experience.',
	// 	image: '/images/tf.webp',
	// 	bgimage: '/images/bg_cans.webp',
	// 	bgimageOn: '/images/bg_cans_red.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'left',
	// 	tags: [
	// 		'HTML Canvas API',
	// 		'Custom Animations',
	// 		'Mobile Responsive',
	// 		'SASS Variables',
	// 	],
	// 	// icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
	// 	icons: [
	// 		{ name: 'SiJavascript', color: '#F7DF1E' },
	// 		{ name: 'SiHtml5', color: '#E44F26' },
	// 		{ name: 'SiSass', color: '#CD6799' },
	// 	],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	source: 'https://terror-fi.netlify.app/',
	// 	visit: 'https://github.com/DaveDevPerry/Terror-Fi_v1',
	// 	login: [],

	// 	font: 'font-terror-fi',
	// 	id: 4,
	// },
	// {
	// 	title: 'Loopy Lotto',
	// 	titleCode: '<p>hel<span>l</span>o</p>',
	// 	subtitle: 'A lottery game with a twist!',
	// 	description:
	// 		'A pay-to-play app in which my family members all participate and can check game progress based on the real life lottery draws. I designed this from scratch and it is developed using vanilla javascript.',
	// 	image: '/images/ll.webp',
	// 	bgimage: '/images/bg_balls.webp',
	// 	bgimageOn: '/images/bg_balls_red.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'left',
	// 	tags: ['Dynamic HTML Markup', 'Mobile Responsive', 'Font Awesome Icons'],
	// 	// icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
	// 	icons: [
	// 		{ name: 'SiJavascript', color: '#F7DF1E' },
	// 		{ name: 'SiHtml5', color: '#E44F26' },
	// 		{ name: 'SiSass', color: '#CD6799' },
	// 	],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	source: 'https://relaxed-dijkstra-f29d44.netlify.app/',
	// 	visit: 'https://github.com/DaveDevPerry/LoopyLottoMVP',
	// 	login: [],

	// 	font: 'font-loopy-lotto',
	// 	id: 5,
	// },

	// {
	// 	title: 'AmWorld',
	// 	titleCode: '<p>hel<span>l</span>o</p>',
	// 	subtitle: 'Courier & Logistics',
	// 	description:
	// 		'A pay-to-play app in which my family members all participate and can check game progress based on the real life lottery draws. I designed this from scratch and it is developed using vanilla javascript.',
	// 	image: '/images/ll.webp',
	// 	bgimage: '/images/bg_balls.webp',
	// 	bgimageOn: '/images/bg_balls_red.webp',
	// 	bgid: 'card-temp',
	// 	bgidOn: 'card-temp-on',
	// 	cardclass: 'left',
	// 	tags: ['Dynamic HTML Markup', 'Mobile Responsive', 'Font Awesome Icons'],
	// 	// icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
	// 	icons: [
	// 		{ name: 'SiJavascript', color: '#F7DF1E' },
	// 		{ name: 'SiHtml5', color: '#E44F26' },
	// 		{ name: 'SiSass', color: '#CD6799' },
	// 	],
	// 	// colors: ['#000000', '#fff444', '#dd66uu'],
	// 	source: 'https://relaxed-dijkstra-f29d44.netlify.app/',
	// 	visit: 'https://github.com/DaveDevPerry/LoopyLottoMVP',
	// 	login: [],

	// 	font: 'font-loopy-lotto',
	// 	id: 6,
	// },
];

// 	// {
// 	// 	title: 'guitARCHIVE',
// 	// 	titleCode: '<h3>guit<span>ARCHIVE</span></h3>',
// 	// 	subtitle: 'An easy to access storage solution for my sheet music',
// 	// 	description:
// 	// 		'A storage solution for all my sheet music that I can access from any device.  Allowing me to track my progress and songs to prioritize practicing to upload to my YouTube channel.',
// 	// 	image: '/images/ga.webp',
// 	// 	bgimage: '/images/bg_guitar1.webp',
// 	// 	bgid: 'card-temp',
// 	// 	cardclass: 'right',
// 	// 	tags: ['3rd Party API', 'React', 'Node'],
// 	// 	icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
// 	// 	source: 'https://heuristic-newton-ad6a42.netlify.app/',
// 	// 	visit: 'https://github.com/DaveDevPerry/guitARCHIVE',
// 	// 	font: 'font-guitar-archive',
// 	// 	id: 1,
// 	// },

// 	{
// 		title: "Pinks N' Purples",
// 		titleCode: `<p>TEST</p>`,
// 		subtitle: 'A custom two-player game of naughts & crosses',
// 		description:
// 			'A game specifically built for my four and six year-old nieces to play on their tablet together. It is a re-imagining of Tic-Tac-Toe.',
// 		image: '/images/pp.webp',
// 		bgimage: '/images/bg_game.webp',
// 		bgid: 'card-temp',
// 		cardclass: 'left',
// 		tags: ['Vanilla JS', 'LocalStorage', 'ES6 modules'],
// 		icons: ['SiHtml5', 'SiSass', 'SiJavascript'],
// 		colors: ['#000000', '#fff444', '#dd66uu'],
// 		source: 'https://bit.ly/pinks-and-purples',
// 		visit: 'https://github.com/DaveDevPerry/pinks-and-purples',
// 		font: 'font-pinks-n-purples',
// 		id: 4,
// 	},

// 	// {
// 	// 	title: 'TV Times',
// 	// 	titleCode: `<p>TEST</p>`,
// 	// 	subtitle: 'Terrorvision tour and gig listings site',
// 	// 	description:
// 	// 		'A CRUD based, fully responsive band gig history site enabling the users to add dates and set lists for missing gigs.',
// 	// 	image: '/images/tvtimes.png',
// 	// 	bgimage: '/images/bg_band.png',
// 	// 	bgid: 'card-temp',
// 	// 	cardclass: 'right',
// 	// 	tags: ['GraphCMS', 'Next.js', 'Firebase'],
// 	// 	source: 'https://goofy-swartz-1ec98c.netlify.app/',
// 	// 	visit: 'https://github.com/DaveDevPerry/tic-tac-toe',
// 	// 	font: 'font-tv-times',
// 	// 	id: 6,
// 	// },
// ];

// export const TimeLineData = [
// 	{ year: 2020, text: 'Coded my first app' },
// 	{ year: 2021, text: 'Building Portfolio Projects' },
// 	{ year: 2022, text: 'Looking for employment' },
// ];
